# Generated by Django 3.0.2 on 2020-02-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_second'),
    ]

    operations = [
        migrations.CreateModel(
            name='a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second', models.CharField(max_length=300)),
            ],
        ),
    ]
