# Generated by Django 3.0.2 on 2020-02-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='a',
        ),
    ]
