# Generated by Django 3.0.2 on 2020-02-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='second',
        ),
    ]
