# Generated by Django 3.0.2 on 2020-02-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_about_second'),
    ]

    operations = [
        migrations.DeleteModel(
            name='a',
        ),
    ]
