# Generated by Django 3.0.2 on 2020-02-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_testimonial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
