# Generated by Django 3.0.2 on 2020-02-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_testimonial_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
