# Generated by Django 3.0.2 on 2020-02-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_remove_index_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='index',
        ),
    ]
