# Generated by Django 3.0.2 on 2020-02-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='card2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title2', models.CharField(max_length=50)),
                ('Description12', models.CharField(max_length=50)),
                ('Description22', models.CharField(max_length=50)),
            ],
        ),
    ]
