# Generated by Django 3.0.2 on 2020-02-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_card2'),
    ]

    operations = [
        migrations.CreateModel(
            name='card3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title2', models.CharField(max_length=50)),
                ('Description13', models.CharField(max_length=50)),
                ('Description23', models.CharField(max_length=50)),
            ],
        ),
    ]
