# Generated by Django 3.0.2 on 2020-02-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_card2_card3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='card',
        ),
        migrations.DeleteModel(
            name='card2',
        ),
        migrations.DeleteModel(
            name='card3',
        ),
    ]
